configured_endpoints: 12
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/perigon%2Fperigon-sdk-df0adb66dcb558806233c4572ff6b045ead5f33965ad740cd9ebfcd35d08f36b.yml
openapi_spec_hash: be7ac3cf078a2b3f870baef2fdd0fba4
config_hash: e34b71f512bb740dd356fd497f00a8b1
